[workspace]
members = [
  "athena/microkernel", "athena/sync", "athena/trie",
  "athena/userspace/booter",
  "athena/userspace/librs",
]

resolver = "2"
default-members = ["athena/microkernel"]

[profile.dev]
debug = "full"
opt-level = 1

[profile.release]
debug = "full"
