[workspace]
members = [
  "athena/kapi",
  "athena/microkernel",
  "athena/sync",
  "athena/trie",
  "athena/userspace/booter",
  "athena/userspace/librs",
]

resolver = "2"
default-members = ["athena/microkernel"]

[workspace.dependencies]
sync = { path = "athena/sync" }
trie = { path = "athena/trie" }
kapi = { path = "athena/kapi" }

[profile.dev]
debug = "full"
opt-level = 1

[profile.release]
debug = "full"
