[workspace]
members = [
  "athena/microkernel",
  "athena/userspace/booter",
  "athena/userspace/librs",
]

resolver = "2"
default-members = ["athena/microkernel"]

[profile.dev]
debug = "full"
opt-level = 2

[profile.release]
debug = "full"
