[toolchain]
channel = "nightly-2024-06-22"
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
  "miri",
]
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-none"]
