[toolchain]
channel = "nightly-2024-03-05"
components = [
  "cargo",
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
]
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-none"]
