[toolchain]
channel = "nightly-2023-06-07"
components = [
  "cargo",
  "clippy",
  "llvm-tools-preview",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
]
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-none"]
