[package]
name = "memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
static_assertions = "1.1.0"

[dev-dependencies]
env_logger = "0.9.0"
