name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check code format
      working-directory: builder/
      run: cargo fmt --check

  build:
    name: Check that code compiles
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings

    steps:
    - uses: actions/checkout@v3
    - name: cargo check
      working-directory: builder/
      run: cargo check

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["athena/bitalloc", "athena/singleton", "athena/framed"] }
    
    steps:
    - uses: actions/checkout@v3
    - name: Run the tests
      working-directory: ${{ matrix.dir }}
      run: cargo test
