name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check code format
      run: cargo fmt --check

  build:
    name: Check that code compiles
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1
    - name: cargo check
      run: make check

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run the tests
      run: cargo test --workspace --exclude x64 --exclude kernel
