name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings

    steps:
    - uses: actions/checkout@v3
    - name: Check code format
      run: cargo fmt --check
    - name: Build/Check
      run: cargo check
    - name: Bitalloc Tests
      run: cd bitalloc && cargo test
    - name: Framed tests
      run: cd framed && cargo test
